export const REQUEST_BLOCKS = 'REQUEST_BLOCKS';
export const RECEIVE_BLOCKS = 'RECEIVE_BLOCKS';

export const REQUEST_SYNC_STATUS = 'REQUEST_SYNC_STATUS';
export const RECEIVE_SYNC_STATUS = 'RECEIVE_SYNC_STATUS';

export const REQUEST_BTC_NODE_INFO = 'REQUEST_BTC_NODE_INFO';
export const RECEIVE_BTC_NODE_INFO = 'RECEIVE_BTC_NODE_INFO';

export const REQUEST_LAST_BLOCK = 'REQUEST_LAST_BLOCK';
export const RECEIVE_LAST_BLOCK = 'RECEIVE_LAST_BLOCK';

export const REQUEST_BLOCK = 'REQUEST_BLOCK';
export const RECEIVE_BLOCK = 'RECEIVE_BLOCK';

export const RECEIVE_LATEST_TRANSACTION = 'RECEIVE_LATEST_TRANSACTION';
export const WAITING_LATEST_TRANSACTION = 'WAITING_LATEST_TRANSACTION';
export const REQUEST_TXS_OF_BLOCK = 'REQUEST_TXS_OF_BLOCK';
export const RECEIVE_TXS_OF_BLOCK = 'RECEIVE_TXS_OF_BLOCK';

export const CONNECT = 'CONNECT';
export const DISCONNECT = 'DISCONNECT';

export const CHANGE_UNIT = 'CHANGE_UNIT';
export const REQUEST_PRICE = 'REQUEST_PRICE';
export const RECEIVE_PRICE = 'RECEIVE_PRICE';
